# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloemweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowergroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bloemweb.FlowerGroup'),
        ),
    ]
